/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateRenovationBudgetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPauser"
      | "addRoomRequirement"
      | "approveProject"
      | "bids"
      | "calculateBudget"
      | "compareBidWithBudget"
      | "createProject"
      | "decryptionRequestCounter"
      | "decryptionRequests"
      | "getAllPausers"
      | "getBudgetEstimate"
      | "getContractorBid"
      | "getDecryptionRequest"
      | "getPauserAtIndex"
      | "getPauserCount"
      | "getProjectContractors"
      | "getProjectInfo"
      | "isContractPaused"
      | "isPaused"
      | "isPauser"
      | "isPauserAddress"
      | "isProjectApproved"
      | "isProjectCalculated"
      | "isProjectValid"
      | "isPublicDecryptAllowed"
      | "kmsGeneration"
      | "nextProjectId"
      | "owner"
      | "pause"
      | "pauserAddresses"
      | "processBudgetReveal"
      | "projectContractors"
      | "projects"
      | "protocolId"
      | "removePauser"
      | "requestBudgetDecryption"
      | "requestDecryption"
      | "submitBid"
      | "submitDecryptionResponse"
      | "unpause"
      | "updateKmsGeneration"
      | "verifiedContractors"
      | "verifyContractor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidSubmitted"
      | "BudgetCalculated"
      | "ContractPaused"
      | "ContractUnpaused"
      | "ContractorVerified"
      | "DecryptionRequested"
      | "DecryptionResponse"
      | "KmsGenerationUpdated"
      | "PauserAdded"
      | "PauserRemoved"
      | "ProjectApproved"
      | "ProjectCreated"
      | "RoomAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addRoomRequirement",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveProject",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bids",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateBudget",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "compareBidWithBudget",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createProject",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionRequestCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decryptionRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPausers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBudgetEstimate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractorBid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecryptionRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPauserCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectContractors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isContractPaused",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isPaused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPauserAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProjectApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProjectCalculated",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isProjectValid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPublicDecryptAllowed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "kmsGeneration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextProjectId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pauserAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processBudgetReveal",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "projectContractors",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removePauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestBudgetDecryption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryption",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDecryptionResponse",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateKmsGeneration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedContractors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyContractor",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addRoomRequirement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "compareBidWithBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionRequestCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decryptionRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPausers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBudgetEstimate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractorBid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecryptionRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPauserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectContractors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isContractPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPaused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPauserAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProjectApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProjectCalculated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProjectValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPublicDecryptAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "kmsGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextProjectId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pauserAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processBudgetReveal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "projectContractors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removePauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestBudgetDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitDecryptionResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateKmsGeneration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedContractors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyContractor",
    data: BytesLike
  ): Result;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [projectId: BigNumberish, contractor: AddressLike];
  export type OutputTuple = [projectId: bigint, contractor: string];
  export interface OutputObject {
    projectId: bigint;
    contractor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetCalculatedEvent {
  export type InputTuple = [projectId: BigNumberish, homeowner: AddressLike];
  export type OutputTuple = [projectId: bigint, homeowner: string];
  export interface OutputObject {
    projectId: bigint;
    homeowner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractPausedEvent {
  export type InputTuple = [by: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [by: string, timestamp: bigint];
  export interface OutputObject {
    by: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUnpausedEvent {
  export type InputTuple = [by: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [by: string, timestamp: bigint];
  export interface OutputObject {
    by: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractorVerifiedEvent {
  export type InputTuple = [contractor: AddressLike];
  export type OutputTuple = [contractor: string];
  export interface OutputObject {
    contractor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requester: AddressLike,
    kmsGeneration: BigNumberish,
    encryptedValue: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    requester: string,
    kmsGeneration: bigint,
    encryptedValue: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    requester: string;
    kmsGeneration: bigint;
    encryptedValue: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecryptionResponseEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    kmsNode: AddressLike,
    encryptedShare: BytesLike,
    signature: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    kmsNode: string,
    encryptedShare: string,
    signature: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    kmsNode: string;
    encryptedShare: string;
    signature: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KmsGenerationUpdatedEvent {
  export type InputTuple = [
    oldGeneration: BigNumberish,
    newGeneration: BigNumberish
  ];
  export type OutputTuple = [oldGeneration: bigint, newGeneration: bigint];
  export interface OutputObject {
    oldGeneration: bigint;
    newGeneration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserAddedEvent {
  export type InputTuple = [pauser: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [pauser: string, timestamp: bigint];
  export interface OutputObject {
    pauser: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserRemovedEvent {
  export type InputTuple = [pauser: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [pauser: string, timestamp: bigint];
  export interface OutputObject {
    pauser: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectApprovedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    selectedContractor: AddressLike
  ];
  export type OutputTuple = [projectId: bigint, selectedContractor: string];
  export interface OutputObject {
    projectId: bigint;
    selectedContractor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [projectId: BigNumberish, homeowner: AddressLike];
  export type OutputTuple = [projectId: bigint, homeowner: string];
  export interface OutputObject {
    projectId: bigint;
    homeowner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoomAddedEvent {
  export type InputTuple = [projectId: BigNumberish, roomIndex: BigNumberish];
  export type OutputTuple = [projectId: bigint, roomIndex: bigint];
  export interface OutputObject {
    projectId: bigint;
    roomIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateRenovationBudget extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateRenovationBudget;
  waitForDeployment(): Promise<this>;

  interface: PrivateRenovationBudgetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPauser: TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;

  addRoomRequirement: TypedContractMethod<
    [
      projectId: BigNumberish,
      area: BigNumberish,
      materialCost: BigNumberish,
      laborCost: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  approveProject: TypedContractMethod<
    [projectId: BigNumberish, selectedContractor: AddressLike],
    [void],
    "nonpayable"
  >;

  bids: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, string, boolean, bigint] & {
        contractor: string;
        bidAmount: string;
        timeEstimate: string;
        isSubmitted: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  calculateBudget: TypedContractMethod<
    [projectId: BigNumberish, contingencyPercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  compareBidWithBudget: TypedContractMethod<
    [projectId: BigNumberish, contractor: AddressLike],
    [[string, string] & { bidAmount: string; budgetEstimate: string }],
    "view"
  >;

  createProject: TypedContractMethod<[], [bigint], "nonpayable">;

  decryptionRequestCounter: TypedContractMethod<[], [bigint], "view">;

  decryptionRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean, bigint] & {
        requestId: bigint;
        requester: string;
        encryptedValue: string;
        timestamp: bigint;
        fulfilled: boolean;
        kmsGeneration: bigint;
      }
    ],
    "view"
  >;

  getAllPausers: TypedContractMethod<[], [string[]], "view">;

  getBudgetEstimate: TypedContractMethod<
    [projectId: BigNumberish],
    [[string, string] & { totalBudget: string; finalEstimate: string }],
    "view"
  >;

  getContractorBid: TypedContractMethod<
    [projectId: BigNumberish, contractor: AddressLike],
    [
      [string, string, boolean, bigint] & {
        bidAmount: string;
        timeEstimate: string;
        isSubmitted: boolean;
        timestamp: bigint;
      }
    ],
    "nonpayable"
  >;

  getDecryptionRequest: TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [string, string, bigint, boolean, bigint] & {
        requester: string;
        encryptedValue: string;
        timestamp: bigint;
        fulfilled: boolean;
        generation: bigint;
      }
    ],
    "view"
  >;

  getPauserAtIndex: TypedContractMethod<
    [_index: BigNumberish],
    [string],
    "view"
  >;

  getPauserCount: TypedContractMethod<[], [bigint], "view">;

  getProjectContractors: TypedContractMethod<
    [projectId: BigNumberish],
    [string[]],
    "view"
  >;

  getProjectInfo: TypedContractMethod<
    [projectId: BigNumberish],
    [
      [string, boolean, boolean, bigint, bigint, bigint] & {
        homeowner: string;
        isCalculated: boolean;
        isApproved: boolean;
        timestamp: bigint;
        roomCount: bigint;
        bidCount: bigint;
      }
    ],
    "view"
  >;

  isContractPaused: TypedContractMethod<[], [boolean], "view">;

  isPaused: TypedContractMethod<[], [boolean], "view">;

  isPauser: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  isPauserAddress: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isProjectApproved: TypedContractMethod<
    [projectId: BigNumberish],
    [boolean],
    "view"
  >;

  isProjectCalculated: TypedContractMethod<
    [projectId: BigNumberish],
    [boolean],
    "view"
  >;

  isProjectValid: TypedContractMethod<
    [projectId: BigNumberish],
    [boolean],
    "view"
  >;

  isPublicDecryptAllowed: TypedContractMethod<[], [boolean], "view">;

  kmsGeneration: TypedContractMethod<[], [bigint], "view">;

  nextProjectId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  pauserAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  processBudgetReveal: TypedContractMethod<
    [
      requestId: BigNumberish,
      decryptedBudget: BigNumberish,
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  projectContractors: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean, boolean, bigint, bigint] & {
        homeowner: string;
        totalBudget: string;
        contingencyPercent: string;
        finalEstimate: string;
        isCalculated: boolean;
        isApproved: boolean;
        timestamp: bigint;
        roomCount: bigint;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  removePauser: TypedContractMethod<
    [_pauser: AddressLike],
    [void],
    "nonpayable"
  >;

  requestBudgetDecryption: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestDecryption: TypedContractMethod<
    [_encryptedValue: BytesLike],
    [bigint],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [
      projectId: BigNumberish,
      bidAmount: BigNumberish,
      timeEstimate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitDecryptionResponse: TypedContractMethod<
    [
      _requestId: BigNumberish,
      _encryptedShare: BytesLike,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateKmsGeneration: TypedContractMethod<
    [_newGeneration: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifiedContractors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  verifyContractor: TypedContractMethod<
    [contractor: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addRoomRequirement"
  ): TypedContractMethod<
    [
      projectId: BigNumberish,
      area: BigNumberish,
      materialCost: BigNumberish,
      laborCost: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveProject"
  ): TypedContractMethod<
    [projectId: BigNumberish, selectedContractor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [string, string, string, boolean, bigint] & {
        contractor: string;
        bidAmount: string;
        timeEstimate: string;
        isSubmitted: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "calculateBudget"
  ): TypedContractMethod<
    [projectId: BigNumberish, contingencyPercent: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "compareBidWithBudget"
  ): TypedContractMethod<
    [projectId: BigNumberish, contractor: AddressLike],
    [[string, string] & { bidAmount: string; budgetEstimate: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "decryptionRequestCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decryptionRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, boolean, bigint] & {
        requestId: bigint;
        requester: string;
        encryptedValue: string;
        timestamp: bigint;
        fulfilled: boolean;
        kmsGeneration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllPausers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBudgetEstimate"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [[string, string] & { totalBudget: string; finalEstimate: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractorBid"
  ): TypedContractMethod<
    [projectId: BigNumberish, contractor: AddressLike],
    [
      [string, string, boolean, bigint] & {
        bidAmount: string;
        timeEstimate: string;
        isSubmitted: boolean;
        timestamp: bigint;
      }
    ],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDecryptionRequest"
  ): TypedContractMethod<
    [_requestId: BigNumberish],
    [
      [string, string, bigint, boolean, bigint] & {
        requester: string;
        encryptedValue: string;
        timestamp: bigint;
        fulfilled: boolean;
        generation: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPauserAtIndex"
  ): TypedContractMethod<[_index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPauserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProjectContractors"
  ): TypedContractMethod<[projectId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getProjectInfo"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [
      [string, boolean, boolean, bigint, bigint, bigint] & {
        homeowner: string;
        isCalculated: boolean;
        isApproved: boolean;
        timestamp: bigint;
        roomCount: bigint;
        bidCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isContractPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauser"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPauserAddress"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProjectApproved"
  ): TypedContractMethod<[projectId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProjectCalculated"
  ): TypedContractMethod<[projectId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProjectValid"
  ): TypedContractMethod<[projectId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPublicDecryptAllowed"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "kmsGeneration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextProjectId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pauserAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "processBudgetReveal"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      decryptedBudget: BigNumberish,
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "projectContractors"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, boolean, boolean, bigint, bigint] & {
        homeowner: string;
        totalBudget: string;
        contingencyPercent: string;
        finalEstimate: string;
        isCalculated: boolean;
        isApproved: boolean;
        timestamp: bigint;
        roomCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removePauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestBudgetDecryption"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDecryption"
  ): TypedContractMethod<[_encryptedValue: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [
      projectId: BigNumberish,
      bidAmount: BigNumberish,
      timeEstimate: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDecryptionResponse"
  ): TypedContractMethod<
    [
      _requestId: BigNumberish,
      _encryptedShare: BytesLike,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateKmsGeneration"
  ): TypedContractMethod<[_newGeneration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifiedContractors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyContractor"
  ): TypedContractMethod<[contractor: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetCalculated"
  ): TypedContractEvent<
    BudgetCalculatedEvent.InputTuple,
    BudgetCalculatedEvent.OutputTuple,
    BudgetCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractPaused"
  ): TypedContractEvent<
    ContractPausedEvent.InputTuple,
    ContractPausedEvent.OutputTuple,
    ContractPausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUnpaused"
  ): TypedContractEvent<
    ContractUnpausedEvent.InputTuple,
    ContractUnpausedEvent.OutputTuple,
    ContractUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractorVerified"
  ): TypedContractEvent<
    ContractorVerifiedEvent.InputTuple,
    ContractorVerifiedEvent.OutputTuple,
    ContractorVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionRequested"
  ): TypedContractEvent<
    DecryptionRequestedEvent.InputTuple,
    DecryptionRequestedEvent.OutputTuple,
    DecryptionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "DecryptionResponse"
  ): TypedContractEvent<
    DecryptionResponseEvent.InputTuple,
    DecryptionResponseEvent.OutputTuple,
    DecryptionResponseEvent.OutputObject
  >;
  getEvent(
    key: "KmsGenerationUpdated"
  ): TypedContractEvent<
    KmsGenerationUpdatedEvent.InputTuple,
    KmsGenerationUpdatedEvent.OutputTuple,
    KmsGenerationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PauserAdded"
  ): TypedContractEvent<
    PauserAddedEvent.InputTuple,
    PauserAddedEvent.OutputTuple,
    PauserAddedEvent.OutputObject
  >;
  getEvent(
    key: "PauserRemoved"
  ): TypedContractEvent<
    PauserRemovedEvent.InputTuple,
    PauserRemovedEvent.OutputTuple,
    PauserRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectApproved"
  ): TypedContractEvent<
    ProjectApprovedEvent.InputTuple,
    ProjectApprovedEvent.OutputTuple,
    ProjectApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoomAdded"
  ): TypedContractEvent<
    RoomAddedEvent.InputTuple,
    RoomAddedEvent.OutputTuple,
    RoomAddedEvent.OutputObject
  >;

  filters: {
    "BidSubmitted(uint256,address)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "BudgetCalculated(uint256,address)": TypedContractEvent<
      BudgetCalculatedEvent.InputTuple,
      BudgetCalculatedEvent.OutputTuple,
      BudgetCalculatedEvent.OutputObject
    >;
    BudgetCalculated: TypedContractEvent<
      BudgetCalculatedEvent.InputTuple,
      BudgetCalculatedEvent.OutputTuple,
      BudgetCalculatedEvent.OutputObject
    >;

    "ContractPaused(address,uint256)": TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;
    ContractPaused: TypedContractEvent<
      ContractPausedEvent.InputTuple,
      ContractPausedEvent.OutputTuple,
      ContractPausedEvent.OutputObject
    >;

    "ContractUnpaused(address,uint256)": TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;
    ContractUnpaused: TypedContractEvent<
      ContractUnpausedEvent.InputTuple,
      ContractUnpausedEvent.OutputTuple,
      ContractUnpausedEvent.OutputObject
    >;

    "ContractorVerified(address)": TypedContractEvent<
      ContractorVerifiedEvent.InputTuple,
      ContractorVerifiedEvent.OutputTuple,
      ContractorVerifiedEvent.OutputObject
    >;
    ContractorVerified: TypedContractEvent<
      ContractorVerifiedEvent.InputTuple,
      ContractorVerifiedEvent.OutputTuple,
      ContractorVerifiedEvent.OutputObject
    >;

    "DecryptionRequested(uint256,address,uint256,bytes32,uint256)": TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;
    DecryptionRequested: TypedContractEvent<
      DecryptionRequestedEvent.InputTuple,
      DecryptionRequestedEvent.OutputTuple,
      DecryptionRequestedEvent.OutputObject
    >;

    "DecryptionResponse(uint256,address,bytes,bytes,uint256)": TypedContractEvent<
      DecryptionResponseEvent.InputTuple,
      DecryptionResponseEvent.OutputTuple,
      DecryptionResponseEvent.OutputObject
    >;
    DecryptionResponse: TypedContractEvent<
      DecryptionResponseEvent.InputTuple,
      DecryptionResponseEvent.OutputTuple,
      DecryptionResponseEvent.OutputObject
    >;

    "KmsGenerationUpdated(uint256,uint256)": TypedContractEvent<
      KmsGenerationUpdatedEvent.InputTuple,
      KmsGenerationUpdatedEvent.OutputTuple,
      KmsGenerationUpdatedEvent.OutputObject
    >;
    KmsGenerationUpdated: TypedContractEvent<
      KmsGenerationUpdatedEvent.InputTuple,
      KmsGenerationUpdatedEvent.OutputTuple,
      KmsGenerationUpdatedEvent.OutputObject
    >;

    "PauserAdded(address,uint256)": TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;
    PauserAdded: TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;

    "PauserRemoved(address,uint256)": TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;
    PauserRemoved: TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;

    "ProjectApproved(uint256,address)": TypedContractEvent<
      ProjectApprovedEvent.InputTuple,
      ProjectApprovedEvent.OutputTuple,
      ProjectApprovedEvent.OutputObject
    >;
    ProjectApproved: TypedContractEvent<
      ProjectApprovedEvent.InputTuple,
      ProjectApprovedEvent.OutputTuple,
      ProjectApprovedEvent.OutputObject
    >;

    "ProjectCreated(uint256,address)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;

    "RoomAdded(uint256,uint8)": TypedContractEvent<
      RoomAddedEvent.InputTuple,
      RoomAddedEvent.OutputTuple,
      RoomAddedEvent.OutputObject
    >;
    RoomAdded: TypedContractEvent<
      RoomAddedEvent.InputTuple,
      RoomAddedEvent.OutputTuple,
      RoomAddedEvent.OutputObject
    >;
  };
}
